### ISSUE TITLE
POST with null relative URI.

### ISSUE THREAD

**Issue by jcoyne** [trellis-ldp/trellis#419] opened 2019-06-21 14:32 UTC
I've posted to a container with a null relative URI as the subject of my triples,  when I ask for it back, it's returning the null relative URI:

```shell
$ curl -H 'Accept: application/n-triples' http://localhost:8080/repository/stanford/2009e668-45fb-4390-899d-c320b6d1a9ef
<> <http://id.loc.gov/ontologies/bibframe/content> <http://id.loc.gov/vocabulary/contentTypes/txt> .
<> <http://www.w3.org/ns/prov#wasGeneratedBy> "resourceTemplate:bf2:Monograph:Work" .
<> <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://id.loc.gov/ontologies/bibframe/Work> .
```

Is this expected?  The LDP spec section 5.2.3.7 reads as follows:
> Commonly, that entity is the model for the "to be created" LDPR, so triples whose subject is the null relative URI result in triples in the created resource whose subject is the created resource.

So, should trellis be returning the absolute URI in those subjects, or is the relative URI expected?

**Comment by ajs6f** [comment] 2019-06-21 14:42
I think our current response is not entirely illegitimate, because I would understand `<>` in that position as `<http://localhost:8080/repository/stanford/2009e668-45fb-4390-899d-c320b6d1a9ef>`, to which you made the request. But is it difficult to interpret that response? Would an absolute IRI be easier to process?

**Comment by jcoyne** [comment] 2019-06-21 14:47
yeah, I definitely think this is a grey area of the spec.  I would prefer it return the assigned absolute IRI.   Failing that your statement that "this is how we want it to behave and we believe it is in spec", would be acceptable too.

**Comment by acoburn** [comment] 2019-06-21 15:51
I also think that it would be clearer if, for n-triples, the absolute IRI were be returned.

**Comment by ajs6f** [comment] 2019-06-21 17:11
Definitely clearer-- was there some use case that lead to us doing what we now do?

**Comment by acoburn** [comment] 2019-06-21 20:15
Not that I know of. I am a little surprised that the IRI isn't expanded. I will look into this over the weekend

**Comment by acoburn** [comment] 2019-06-23 16:18
The only way I was able to reproduce this was by POSTing n-triples with a relative IRI -- the relative IRI is expanded automatically in Turtle and JSON-LD.

However, when reviewing the [N-Triples specification](https://www.w3.org/TR/n-triples/), section 2.2 explicitly states:

> IRIs may be written only as absolute IRIs.

Which tells me that your client really ought to be POSTing these triples as either Turtle or JSON-LD. That is, N-Triples doesn't allow for relative IRIs. The underlying issue here is that the Jena library doesn't apply a "context" to N-Triples parsing, probably because such a concept isn't defined for N-Triples.

The upshot is that this behavior is outside the scope of the N-Triples specification and there is a clear work-around (use Turtle or JSON-LD). Would that work for your purposes?

**Comment by acoburn** [comment] 2019-07-03 16:03
Closing this, as it falls outside the scope of the N-Triples specification, the Trellis handling of it is arguably not incorrect and there is a clear work-around.

**Closed by acoburn** 2019-07-03 16:03 UTC
Labels: question, wontfix
