### ISSUE TITLE
Failing tests involving PATCH

### ISSUE THREAD

**Issue by ajs6f** [trellis-ldp/trellis#301] opened 2018-11-17 22:59 UTC
Got an odd triple of test failures, that I only see intermittently in CI. Here they are:
```
[ERROR] Failures: 
[ERROR]   LdpBinaryIT.testPatchBinaryDescription Check the graph size is greater than 0 ==> expected: <true> but was: <false>
[ERROR]   LdpRdfIT.testPatchRDF Check the graph size ==> expected: <4> but was: <3>
[ERROR]   MementoResourceIT.testMementoContent Check for a dc:title property ==> expected: <true> but was: <false>
```
What I notice (which may or may not have any relevance) is that they all seem to involve PATCHing and then looking for the changes immediately thereafter. I'm wondering if it is possible that `PatchHandler` is somehow returning a result before persistence is complete? I can't see how it would, but I find it a bit hard to trace the HTTP handlers. 

Has anyone else ever seen anything like this with another backend?

**Comment by acoburn** [comment] 2018-11-18 01:41
This is curious. It is also curious that the error is intermittent. I haven't seen that error myself, though I've only worked with synchronous backends. Given what I know about Cassandra, perhaps the data has been persisted to one node (assuming here that the replication factor would be something like 3), but the subsequent request gets stale data, since the data hasn't been replicated fully across the cluster. Is there a way to adjust the consistency levels in Cassandra? Such as: for writes, wait until at least two nodes have successfully written the resource and for reads, wait until at least two nodes agree on a response.

**Comment by ajs6f** [comment] 2018-11-18 02:31
No, there's but one node in play. I'll look at tracing through the thing more carefully, but it's difficult because I can't reproduce it locally. 

Actually, if you have the time, it might be informative if you cloned it and built it locally, just to see whether you see the same thing or no.

**Comment by ajs6f** [comment] 2018-11-26 15:50
After I changed a certain part of the C* setup to use [Version 1 UUIDs](https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_1_(date-time_and_MAC_address)) instead of [simple timestamps](https://docs.datastax.com/en/cql/3.3/cql/cql_reference/timestamp_type_r.html) (but for reasons I do not really understand), the tests that sometimes fail in CI have changed to:
```
[ERROR]   LdpBinaryIT.testPatchBinaryDescription Check the graph size is greater than 0 ==> expected: <true> but was: <false>
[ERROR]   LdpRdfIT.testPatchRDF Check the graph size ==> expected: <4> but was: <3>
````

so… progress? It seems more and more that something is going on with `PATCH`, but I'm not sure what. I've traced the HTTP machinery loosely, I suppose I now need to trace it in detail.

@acoburn is it true to say that all the behavioral differences between, say, `PUT` and  `PATCH` would all be found in [`PutHandler`](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/PutHandler.java) vs. [`PatchHandler`](https://github.com/trellis-ldp/trellis/blob/master/core/http/src/main/java/org/trellisldp/http/impl/PatchHandler.java)?

**Comment by acoburn** [comment] 2018-11-26 16:07
Yes, the differences would be found in the two classes mentioned. From the perspective of the `ResourceService`, both will issue `ResourceService::replace`.

**Comment by ajs6f** [comment] 2018-11-26 16:21
But from the POV of `TrellisHttpResource` they are substantially the same, right? In particular, they both retrieve, compute, and then replace the resource while simultaneously `touch`ing its container, yes?

I suspect this has to do with bad timing-- tests getting run before something has settled (notice that the two failures are both _missing_ info, not find more than they should).

**Comment by acoburn** [comment] 2018-11-26 16:23
Correct. And I think you are right that this is related to timing. Also, I tried reproducing this error locally with no success.

**Comment by ajs6f** [comment] 2018-12-08 22:32
I have a lead now on this: Cassandra's materialized views (used in `trellis-cassandra` for containment indexing) are [updated asynchronously with their source tables](https://docs.datastax.com/en/cql/3.3/cql/cql_using/useCreateMV.html). Since the missing triples seem to be containment triples, this smells bad.

**Comment by acoburn** [comment] 2018-12-09 00:14
I thought the failing tests were for binary descriptions, which wouldn't have containment triples.

In any case, I the question is also one of test expectations. I don't want the tests to explicitly require a strict degree of consistency (hence the wait for [ETags to change](https://github.com/trellis-ldp/trellis/blob/master/components/test/src/main/java/org/trellisldp/test/LdpBinaryTests.java#L186)), though perhaps we should add in an extra pause just to be sure, sort of like we're doing [here](https://github.com/trellis-ldp/trellis/blob/master/components/test/src/main/java/org/trellisldp/test/LdpBinaryTests.java#L178).

**Comment by ajs6f** [comment] 2018-12-09 01:13
No, there is `LdpRdfIT.testPatchRDF` and `LdpBinaryIT.testPatchBinaryDescription`. Is `PATCH` the commonality?

**Comment by ajs6f** [comment] 2018-12-09 16:47
Hm, this did seem to be a red herring. I don't know why I mistakenly remembered the triples as being containment triples-- they're not. I'm left with `PATCH` being the likely commonality, but little more than that to go on…

**Comment by ajs6f** [comment] 2018-12-09 17:54
Another data point: running [just the three failing tests in CI succeeds](https://circleci.com/gh/ajs6f/trellis-cassandra/115). Really annoying. There is something subtle going on here.

**Comment by ajs6f** [comment] 2018-12-09 18:10
After further wrangling with CI, it appears that running _any other test_ with the three suspect tests will cause all three to fail.

**Comment by ajs6f** [comment] 2018-12-09 19:37
I'm finding it increasingly suspicious that the two `PATCH`-related failing tests both use (and as far as I can see, are the only tests that use) the technique:
```
await().until(() -> !oldETag.equals(getETag(resourceLocation)));
```
but I'm not sure what to do with that. Since `PatchHandler` ends up calling `ResourceService:replace`, I don't know what would be different about it.

**Comment by acoburn** [comment] 2018-12-10 02:31
I really don't have anything helpful to add, so please do keep adding any new data points to this issue.

**Comment by ajs6f** [comment] 2019-10-24 15:14
Closing in favor of https://github.com/trellis-ldp/trellis/issues/563

**Comment by ajs6f** [comment] 2019-10-24 16:43
Reopening because I was able to fail either these or the failing Memento tests in #563  independently, so they are not related (at least not certainly).

**Comment by acoburn** [comment] 2019-11-19 15:51
After migrating the trellis-cassandra tests into the trellis-extensions repo and reworking the queries a bit, these test failures have disappeared. Once https://github.com/trellis-ldp/trellis-extensions/pull/29 is merged, I think we can close this issue.

**Closed** 2019-11-19 19:44 UTC
Labels: area/http, testing
